www:
  - changed-files:
      - any-glob-to-any-file:
          - packages/www/src/**/*
          - packages/www/public/**/*

blog:
  - changed-files:
      - any-glob-to-any-file:
          - packages/blog/src/**/*
          - packages/blog/public/**/*

post:
  - changed-files:
      - any-glob-to-any-file: packages/blog/posts/**/*

moment:
  - changed-files:
      - any-glob-to-any-file:
          - packages/moment/src/**/*
          - packages/moment/public/**/*

chore:
  - all:
      - changed-files:
          - any-glob-to-any-file: "**"
          - all-globs-to-all-files: "!packages/**/src/**/*"

docs:
  - changed-files:
      - any-glob-to-any-file: "docs/**"
